name=UCF_RSLK
version=0.3
author=Don Harper <harper@ucf.edu>
maintainer=Don Harper <harper@ucf.edu>
sentence=This library providers Energia drivers for the TI RSLK robotics kit.
paragraph=This library provides several apis to interact with the TI RSLK robotics basic and advanced kit.
category=Sensors
url=https://github.com/ucfinnovationlab/UCF_RSLK_LIBRARY
architectures=msp432r
